# Generated by Django 2.2.2 on 2019-07-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0005_judge_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('member_names', models.CharField(max_length=100)),
                ('member_emails', models.EmailField(max_length=254)),
                ('new_hackers', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.TextField(blank=True)),
            ],
        ),
    ]
