# Generated by Django 2.2.2 on 2019-07-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0006_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='member_emails',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member_names',
        ),
        migrations.AddField(
            model_name='team',
            name='member_four_email',
            field=models.EmailField(default='invalid', max_length=254),
        ),
        migrations.AddField(
            model_name='team',
            name='member_four_name',
            field=models.CharField(default='invalid', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='member_one_email',
            field=models.EmailField(default='invalid', max_length=254),
        ),
        migrations.AddField(
            model_name='team',
            name='member_one_name',
            field=models.CharField(default='invalid', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='member_three_email',
            field=models.EmailField(default='invalid', max_length=254),
        ),
        migrations.AddField(
            model_name='team',
            name='member_three_name',
            field=models.CharField(default='invalid', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='member_two_email',
            field=models.EmailField(default='invalid', max_length=254),
        ),
        migrations.AddField(
            model_name='team',
            name='member_two_name',
            field=models.CharField(default='invalid', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='new_hackers',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4')], max_length=1),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
